import mongoose from "mongoose";
const cartCollection = "carts";
const cartSchema = new mongoose.Schema({
  // ID automatically generated by MongoDB
  products: [
    {
        product: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "products"
          },
        quantity: Number,
    },
  ],
});

export const cartModel = mongoose.model(cartCollection, cartSchema);